# Local development compose file
# This builds the application from source including the shared types package
services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: otpshare
    restart: unless-stopped
    ports:
      - "${EXTERNAL_PORT:-3001}:3001"
    env_file:
      - .env
    volumes:
      # Persist database
      - otpshare-data:/app/data
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

volumes:
  otpshare-data:
    driver: local
